### ISSUE TITLE
rotation issues

### ISSUE THREAD

**Issue by antithing** [aliyasineser/GraduationProjectII#1]
Hi, thanks for making this code available. I have converted it to c++, and am trying to get the relative position between aruco markers, as you were.

My problem is this:

If the markers are all up the same way, eg: the 0 corner point is the same on all of them, it works great.

As soon as I rotate a marker , the offset makes my relative position incorrect.

Did you see this behaviour? If so, how did you fix it? 
Thanks again.

**Comment by aliyasineser** [comment]
Hi,
If you can provide video or image with relative coordinate values( aruco tvec and rvec ), we can solve the problem fast. 
I didn't understand that how the markers can be all up the same way? You mean they are in difference places but rotations are same or anything else?  In my code I am using relative position for once, to calibrate. If you want the relative position all the time ( in every frame, you want the distance and rotation between them ) you need to call relative position function all the time. For my part, doing it once is working because the thing I did was basically estimate a point ( needle's point ) and from now on even tho I don't see the needle I can see marker and know where is the needle exactly.
After the detailed data, we can solve it. Thanks for consider the code valuable. Hope it helps.

**Comment by antithing** [comment]
Hi, thanks for getting back to me. What I mean is, in this image:

![fbtvr](https://user-images.githubusercontent.com/11506730/44526561-4aa2cf80-a6dc-11e8-9591-4a99cf38b72f.jpg)

The first corner is at bottom left in two of the markers, and at top left in the middle one. this is causing my relative transform to be incorrect. 

I set marker 11 as the Origin (zero point) then i run this:

```
void relativePosition(cv::Mat rvec1, cv::Mat tvec1, cv::Mat rvec2, cv::Mat tvec2, cv::Mat &composedRvec, cv::Mat &composedTvec)
{
	// Inverse the second marker, the right one in the image
	cv::Mat invRvec, invTvec, orgRvec, orgTvec;
	inversePerspective(rvec2, tvec2, invRvec, invTvec);
	cv::composeRT(rvec1, tvec1, invRvec, invTvec, composedRvec, composedTvec);
	
}

```

with:

`relativePosition(OriginRv, OriginTv, rvec, tvec, composedR, composedT);`

on the other two markers.


it gives me:

marker 11 is the origin.

marker id 10 
otv: [-9.217621478868324;
 0.9650507963509595;
 98.74599647851751]
tv: [4.486225101319966;
 0.5879587708100423;
 98.70206175243368]
composed: [-13.69191388735148;
 -0.1498302858635121;
 -0.6697646870434681]

marker id 17
otv: [-9.217621478868324;
 0.9650507963509595;
 98.74599647851751]
tv: [17.63047308895615;
 0.8240868439570559;
 98.99678221761631]
difference: [0.9305345929995816;
 26.80310458825741;
 -1.276963604737404]

When i plot the marker corners using this info, I get:

![capture](https://user-images.githubusercontent.com/11506730/44526931-54790280-a6dd-11e8-8084-3f7d6644406e.JPG)

Thank you very much for your help!

**Comment by aliyasineser** [comment]
As you can see in the translation vectors, they are look alike and id 17 is a bit further in X. It is totally right. Rotation is different as you saw. While transforming, if you use composeRT it may add the first rotation and after that translation. If you know, translation and rotation operations has to be ordered safely. If you first rotate and after that translate, it will be different than first translating and after that rotating. I suggest that put all of your markers in the same rotation space ( all of the first corners will be top left  so XYZ rotations will be in the same space ) or write an extra function to see if their rotation space are same or not ( their xyz axis should look at the same side ). Since id 10 has different axis, even tho you get the rotation difference it will have an effect. As you can see id 17 and id 11 are in the same rotation space it can calculate the same thing. But if the spaces are not correct to each other, I think it will be like id 10-11. I guess that xyz difference in the tvec is perfectly right but if you add marker  11's X and difference between 10-11 X it will go upwards. Because in the real world, marker 10's Y axis and marker 11's X axis are the same. So you should rotate 90 degree clockwise the marker 10 or allign all of the markers xyz axis. 
Sorry for the long post, I just couldn't make it simpler.

**Comment by antithing** [comment]
Thank you! That is what i thought was happening, it is correct, technically, but is wrong in world space. I will need to run this on random marker placement, so i will need to be able to handle different rotations. 

`write an extra function to see if their rotation space are same or not ( their xyz axis should look at the same side )`

What would this function look like? If I knew the difference, i could write a workaround for it . perhaps get the rotation difference, negate it, composeRT and re-rotate?

**Comment by aliyasineser** [comment]
You know that they all almost parallel to the camera. Even they are not, you printed in the same paper so their rotation should same or there is a slight difference. You can get absolute difference and check if their rotation is smaller than an epsilon( 5-10 degrees, it may change according is camera calibration well or not ). If the difference is small in all axis, they should be in the same rotation space. So you can seperately get rotation difference and check, return false even if one of them are different. Also you can return the how much they are different and do the rotation. Unfortunately I didn't know the exact rotating function but you can use homogeneous coordinate system.

**Comment by antithing** [comment]
So something like:

cv::Vec3d

marker12Diff = abs(M1Rvec - M2Rvec);

if(marker12Diff.x < epsilon && marker12Diff.y < epsilon && marker12Diff.z < epsilon )
{

..same rotation space

}

**Comment by aliyasineser** [comment]
Yes, but with only one if statement you can't which one is different. I also realized that it will be random marker placement, so I suggest that you change you camera center to aruco center. If you do that, you can check that if all of the markers have the same rotation to the camera or not. But the first solution can work also, if you can guarantee that their plane will be same. 
I am also testing the perspective inversion and I realized that you can easily work with homogeneous matrices. Just suggesting, it is really nice, you just need a bit of theory.

**Comment by antithing** [comment]
Ah actually they will be on different planes. some on floor, some on walls etc. So the first option will not work?

**Comment by aliyasineser** [comment]
It won't because the differences will have a meaning if their at least one plane is right. Think that  their x and y axis are different. Z axis will be the anchor point. but if their x and y different but they look each other at the same time, z difference will be also 180 degrees so you won't have an anchor point. 
I have no idea for now but I can suggest that you can calculate the rotations one by one. You calculate  and apply the difference, make X axis correct. Then Y and Z. But it has no meaning because the thing you are doing right now the same as this one. Hope you can find a solution and I will gladly read the code when you did. But for now, I need to focus on aruco marker based drone landing. 
Thanks for review on the code, I wish you a great coding.
